### ISSUE TITLE
Unnamed Resource

### ISSUE THREAD

**Issue by Bartoncl** [mradamcox/afrh#25]
A few resources have come up as Unnamed Resource but have names assigned to them. One I have been able to track down is the Viewing Stand. 

![image](https://cloud.githubusercontent.com/assets/21131807/24007258/698c3944-0a44-11e7-9147-2dbd069bb8d7.png)

**Comment by mradamcox** [comment]
This is because none of the names are defined as "Primary" names.
![image](https://cloud.githubusercontent.com/assets/10427268/24007397/6c5cf314-0a3c-11e7-9d0c-6319c5066fb9.png)

**Comment by Bartoncl** [comment]
Ah, thank you!

**Comment by mradamcox** [comment]
fixed it.
![image](https://cloud.githubusercontent.com/assets/10427268/24007476/b7e7a0f4-0a3c-11e7-946a-4a41ae1cac0f.png)
